#!/bin/bash

# Arguments:
#   $1 = <imagename>.png
#   $2 = <username>

# 0. Check for errors #
#   A. Check for the correct number of parameters #
if [ "$#" -ne 2 ]; then
  echo "ERROR:\tIllegal number of parameters:\tExpected 2, there were $#."
  exit 1
#   B. Check that the first parameter ends with ".png" #
elif [[ $1 != *.png ]]; then
  echo "ERROR:\tFirst parameter needs to end with \".png\"."
  exit 2
#   C. Check to see if the username already exists #
elif [ -f ./database/$2.xyt ]; then
  echo "ERROR:\tUsername already exists, choose a more unique name."
  exit 3
fi


# 1. Create the temporary working directory and enter it #
MYCURRDIR=$PWD
MYTMPDIR=`mktemp -d ` || exit 1
trap 'rm -rf $MYTMPDIR; cd $MYCURRDIR' EXIT
#echo $MYTMPDIR ## for debugging purposes

# 2. Convert the candidate PNG image into a WSQ image #
./Cognaxon/convertWSQ.o $1 $MYTMPDIR/image > /dev/null

# 3. Extract the candidate WSQ image's minutiae #
./NBIS/mindtct $MYTMPDIR/image.wsq $MYTMPDIR/$2 > /dev/null

# 4. Store its minutiae in the xyt format #
cp $MYTMPDIR/$2.xyt ./database/$2.xyt


# Finally, delete the temporary directory #

cd $MYCURRDIR
rm -rf $MYTMPDIR


exit 0
