#!/bin/bash

# Arguments:
#   $1 = <imagename>
#   $2 = <username>

# 0. Check for errors #
#   A. Check for the correct number of parameters #
if [ "$#" -ne 2 ]; then
  echo -e "ERROR:\tIllegal number of parameters:\tExpected 2, there were $#."
  exit 2
#   B. Check to see if the username exists #
elif [ ! -f ./database/$2.xyt ]; then
  echo -e "ERROR:\tUsername doesn't exists, make sure the user is enrolled."
  exit 3
fi


# 1. Create the temporary working directory and enter it #
MYCURRDIR=$PWD
MYTMPDIR=`mktemp -d ` || exit 1
trap 'cd $MYCURRDIR; rm -rf $MYTMPDIR' EXIT

# 2. Convert the probing PNG image into a WSQ image #
./Cognaxon/convertWSQ.o $1 $MYTMPDIR/image > /dev/null

# 3. Extract the probing WSQ image's minutiae #
./NBIS/mindtct $MYTMPDIR/image.wsq $MYTMPDIR/minutiae > /dev/null

# 4. Match the probing minutiae to a username's minutiae in xyt format #
SCORE=`./NBIS/bozorth3 $MYTMPDIR/minutiae.xyt ./database/$2.xyt`
echo $SCORE

# 5. Finally, delete the temporary working directory #
cd $MYCURRDIR
rm -rf $MYTMPDIR


exit $SCORE

