#!/bin/bash


# Arguments:
#   $1 = <image-path>


# Wrapper function: echo to stderr
function echoerr() { >&2 echo "$@"; }


# Echo statuses
SCORE=0
FAIL=0

# Exit statuses
SUCCESS=0
ERR_NUM_PARAMS=1
ERR_TMP_DIR=2


# 0. Check for errors #
#   A. Check for the correct number of parameters #
if [ "$#" -ne 1 ]; then
  echoerr "Usage: test-quality IMAGE_PATH"
  echo $FAIL
  exit $ERR_NUM_PARAMS
fi


# 1. Create the temporary working directory and enter it #
MYTMPDIR=$(mktemp -d) || (echo $FAIL && exit $ERR_TMP_DIR)
trap 'rm -rf $MYTMPDIR' EXIT


# 2. Convert the PNG images into WSQ images #
./Cognaxon/convertWSQ $1 $MYTMPDIR/image > /dev/null


# 3. Check to make sure image quality is between 1 and ($QUALITY-1) #
SCORE=$(./NBIS/nfiq $MYTMPDIR/image.wsq)


rm -rf $MYTMPDIR

echo $SCORE
exit $SUCCESS

