#!/bin/bash


# Arguments:
#   $1 = <image-name-A>
#   $2 = <image-name-B>


# Wrapper function: echo to stderr
#function echoerr() { >&2 echo "$@"; }
function echoerr() { :; }

# Images' quality scores must be better than QUALITY
QUALITY=5  # Accept all
#QUALITY=4  # Reject 5
#QUALITY=3  # Reject 4 and 5
#QUALITY=2  # Reject 3, 4, and 5
#QUALITY=1  # Reject 2, 3, 4, and 5

# Exit statuses
SUCCESS=0
ERR_NUM_PARAMS=1
ERR_TMP_DIR=2
ERR_QUALITY_A=3
ERR_QUALITY_B=4
ERR_QUALITY_A_B=5



# 0. Check for errors #
#   A. Check for the correct number of parameters #
if [ "$#" -ne 2 ]; then
  echoerr -e "ERROR:\tIllegal number of parameters:\tExpected 2, there were $#."
  echo 0
  exit $ERR_NUM_PARAMS
fi



# 1. Create the temporary working directory and enter it #
MYCURRDIR=$PWD
MYTMPDIR=`mktemp -d ` || (echo 0 && exit $ERR_TMP_DIR)
#trap 'cd $MYCURRDIR; rm -rf $MYTMPDIR; exit $RETURN' EXIT
#trap 'cd $MYCURRDIR; rm -rf $MYTMPDIR; echo $RETURN; exit $RETURN' EXIT  # debugging


# 2. Convert the PNG images into WSQ images #
./Cognaxon/convertWSQ $1 $MYTMPDIR/imageA > /dev/null
./Cognaxon/convertWSQ $2 $MYTMPDIR/imageB > /dev/null


# 3. Check to make sure image quality is between 1 and ($QUALITY-1) #
QUALITYA=$(./NBIS/nfiq $MYTMPDIR/imageA.wsq)
QUALITYB=$(./NBIS/nfiq $MYTMPDIR/imageB.wsq)
if ! [ $QUALITYA -le $QUALITY -a $QUALITYB -le $QUALITY ]; then
  echo 0
  if [ $QUALITYA -le $QUALITY ]; then
    echoerr -e "ERROR:\tImage quality of arg2 ($QUALITYB) is not good enough. Retake image."
    exit $ERR_QUALITY_B
  elif [ $QUALITYB -le $QUALITY ]; then
    echoerr -e "ERROR:\tImage quality of arg1 ($QUALITYA) is not good enough. Retake image."
    exit $ERR_QUALITY_A
  else
    echoerr -e "ERROR:\tImage qualities of both images ($QUALITYA and $QUALITYB) are not good enough. Retake both images."
    exit $ERR_QUALITY_A_B
  fi
fi


# 4. Extract each WSQ image's minutiae #
./NBIS/mindtct $MYTMPDIR/imageA.wsq $MYTMPDIR/minutiaeA > /dev/null
./NBIS/mindtct $MYTMPDIR/imageB.wsq $MYTMPDIR/minutiaeB > /dev/null
#debug
./NBIS/mindtct $MYTMPDIR/imageA.wsq ./minutiae

# 5. Match the two minutiaes in xyt format #
SCORE=$(./NBIS/bozorth3 $MYTMPDIR/minutiaeA.xyt $MYTMPDIR/minutiaeB.xyt)


#echoerr -e "$1 vs $2 = $SCORE"

echo $SCORE
exit $SUCCESS

