#!/bin/bash

# Arguments:
#   $1 = <image-name-A>
#   $2 = <image-name-B>

# 0. Check for errors #
#   A. Check for the correct number of parameters #
if [ "$#" -ne 2 ]; then
  echo -e "ERROR:\tIllegal number of parameters:\tExpected 2, there were $#."
  exit 2
fi


# 1. Create the temporary working directory and enter it #
MYCURRDIR=$PWD
MYTMPDIR=`mktemp -d ` || exit 1
trap 'cd $MYCURRDIR; rm -rf $MYTMPDIR' EXIT
echo $MYTMPDIR ## debugging

# 2. Convert the PNG images into WSQ images #
./../Cognaxon/convertWSQ.o $1 $MYTMPDIR/imageA > /dev/null
./../Cognaxon/convertWSQ.o $2 $MYTMPDIR/imageB > /dev/null

# 3. Extract each WSQ image's minutiae #
./../NBIS/mindtct $MYTMPDIR/imageA.wsq $MYTMPDIR/minutiaeA > /dev/null
./../NBIS/mindtct $MYTMPDIR/imageB.wsq $MYTMPDIR/minutiaeB > /dev/null

# 4. Match the two minutiaes in xyt format #
SCORE=`./../NBIS/bozorth3 $MYTMPDIR/minutiaeA.xyt $MYTMPDIR/minutiaeB.xyt`
echo $SCORE

# Finally, delete the temporary directory #

cd $MYCURRDIR
rm -rf $MYTMPDIR


exit $SCORE
