#!/bin/bash

# Arguments:
#   $1 = <image-name-A>
#   $2 = <image-name-B>

#QUALITY=4 # Images' quality scores must be better than QUALITY
QUALITY=5

# To Return:
FAIL=0
# SUCCESS -> RETURN > 0
# Should never be below 0 (undefined behavior)
###echo "args: '$1' '$2'"
# 0. Check for errors #
#   A. Check for the correct number of parameters #
if [ "$#" -ne 2 ]; then
  echo -e "ERROR:\tIllegal number of parameters:\tExpected 2, there were $#."
  exit $FAIL
fi

# 1. Create the temporary working directory and enter it #
MYCURRDIR=$PWD
MYTMPDIR=`mktemp -d ` || exit $FAIL
#trap 'cd $MYCURRDIR; rm -rf $MYTMPDIR; exit $RETURN' EXIT
#trap 'cd $MYCURRDIR; rm -rf $MYTMPDIR; echo $RETURN; exit $RETURN' EXIT  # debugging

# 2. Convert the PNG images into WSQ images #
./Cognaxon/convertWSQ $1 $MYTMPDIR/imageA > /dev/null
./Cognaxon/convertWSQ $2 $MYTMPDIR/imageB > /dev/null

# 3. Check to make sure image quality is between 1 and ($QUALITY-1) #
QUALITYA=$(./NBIS/nfiq $MYTMPDIR/imageA.wsq)
QUALITYB=$(./NBIS/nfiq $MYTMPDIR/imageB.wsq)
if ! [ $QUALITYA -lt $QUALITY          \
    -a $QUALITYB -lt $QUALITY ]; then
  if [ $QUALITYA -lt $QUALITY ]; then
    echo -e "ERROR:\tImage quality of arg2 ($QUALITYB) is not good enough. Retake image."
  elif [ $QUALITYB -lt $QUALITY ]; then
    echo -e "ERROR:\tImage quality of arg1 ($QUALITYA) is not good enough. Retake image."
  else
    echo -e "ERROR:\tImage qualities of both images ($QUALITYA and $QUALITYB) are not good enough. Retake both images."
  fi
  exit $FAIL
fi

# 4. Extract each WSQ image's minutiae #
./NBIS/mindtct $MYTMPDIR/imageA.wsq $MYTMPDIR/minutiaeA > /dev/null
./NBIS/mindtct $MYTMPDIR/imageB.wsq $MYTMPDIR/minutiaeB > /dev/null

# 5. Match the two minutiaes in xyt format #
SCORE=`./NBIS/bozorth3 $MYTMPDIR/minutiaeA.xyt $MYTMPDIR/minutiaeB.xyt`

echo "$1 vs $2 = $SCORE"

exit $SCORE

