all: estimatethreshold estimatethreshold_v2

estimatethreshold: estimatethreshold.cpp
	g++ -std=c++11 -g -O0 -o estimatethreshold estimatethreshold.cpp

estimatethreshold_v2: estimatethreshold_v2.cpp
	g++ -std=c++11 -g -O0 -o estimatethreshold_v2 estimatethreshold_v2.cpp

clean:
	rm -f estimatethreshold estimatethreshold_v2

